export const Consumption = {
  Fetch: 'FETCH_CONSUMPTIONS',
  FetchSuccess: 'FETCH_CONSUMPTIONS_SUCCESS',
  FetchError: 'FETCH_CONSUMPTIONS_ERROR',

  Delete: 'DELETE_CONSUMPTIONS',
  DeleteSuccess: 'DELETE_CONSUMPTIONS_SUCCESS',
  DeleteError: 'DELETE_CONSUMPTIONS_ERROR',

  Update: 'UPDATE_CONSUMPTIONS',
  UpdateSuccess: 'UPDATE_CONSUMPTIONS_SUCCESS',
  UpdateError: 'UPDATE_CONSUMPTIONS_ERROR',

  Create: 'CREATE_CONSUMPTIONS',
  CreateSuccess: 'CREATE_CONSUMPTIONS_SUCCESS',
  CreateError: 'CREATE_CONSUMPTIONS_ERROR'
}
